### PR TITLE
use explicit definition for `isConsonant`

### LINKED ISSUE #1: definition of `isConsonant`
Currently `isConsonant` returns true for every character which is not a vowel, including numbers and symbols.

Possibly a more correct definition would be just

```haskell
isConsonant :: Char -> Bool
isConsonant = (`elem` "bcdfghjklmnpqrstvwxyz") . toLower
```

### PR DESCRIPTION
**Pull request by marcosh**
this avoids false positives on numbers and symbols

closes #1

### CODE REVIEW

**Comment by Mikolaj** [comment]
Could you extend the comment for the function, explaining why it's not just the negation of `isVowel` or pointing out that the sum of the two sets doesn't cover all letters? Concisely, but along the lines of our discussion in the issue ("this third category of letters"; "warning, you need ad-hoc extensions to handle it").

Also, if that's not too much effort (I don't know), could you add a few tests for one of the functions that use `isConsonant`? Specifically, one of them could be a test that now passes, but would fail if somebody reverted your change. No big problem if it's contrived or unintuitive.

Thank you!

**Comment by Mikolaj** [comment]
I wonder, there is a lot of `'` and some `-` in English words --- could some sensible tests be written, where these are neither vowels nor consonants and the results are right (or wrong, but then let's think about a solution)?

**Comment by marcosh** [comment]
@Mikolaj I added some comments to `isConsonant` and one test case to highlight the issue

**Comment by Mikolaj** [comment]
Yay, a great test! Feel free to merge once you are satisfied.

**Comment by marcosh** [comment]
I guess I don't have the rights to merge! To me this looks good. More improvements could be done in the future

**Comment by Mikolaj** [comment]
Apologies, I've now given you the rights. Successfully, I see. Welcome!

**Comment by marcosh** [comment]
Thank you!

**Pull request merged**
